[package]
name = "hardware-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bool-algebra = { git = "https://github.com/eeli1/bool-algebra", version = "0.1.0" }
either = "1.6.1"